### ISSUE TITLE
Benchmark bot

### ISSUE THREAD

**Issue by maleadt** [JuliaGPU/GemmKernels.jl#115]
It'd be great to have a bot that comments with benchmark results on every pull request. I think we can do this using a Buildkite job that has access to the Github token (which isn't available to third-party PRs, but `bors` could help here), storing previous benchmark results in a branch, and comparing to whatever has been stored.

Open questions/considerations:

- store all commits, for historical purposes?
- it should edit any existing comment

**Comment by thomasfaingnaert** [comment]
I'd definitely keep the benchmark results for all commits.
Some other things to think about:

1. Which GPU architectures will we run the benchmarks on?
2. Which version(s) of Julia will we use?

I suppose we want to get a coverage that is as wide as possible, so Pascal, Volta, Turing, Ampere, Ada Lovelace, and Hopper for (1), and all Julia versions supported in CI/CD for (2)?

**Comment by maleadt** [comment]
> Which GPU architectures will we run the benchmarks on?

The `benchmark` queue currently has a single worker with a NVIDIA GeForce RTX 2070.


> Which version(s) of Julia will we use?

I propose using the latest stable version, and treating a Julia version update as something that we need to benchmark. Benchmarking across all versions of Julia would be better, but I'm not sure how to best manage that. I think it would make the benchmark comment much more heavyweight.
