### ISSUE TITLE
A wrong function name `parallellise`

### ISSUE THREAD

**Issue by ArrogantGao** [JuliaGPU/GemmKernels.jl#177]
I notice that there is a function `parallellise` in `tiling.jl`, while it is called `parallelise` in the article, I suppose that it is a typo?
I also wonder will you release the latest code as a new version recently? The current released `0.1.0` can not work with Julia after `v1.8`, and I am trying to build some new packaged based on that.

**Comment by thomasfaingnaert** [comment]
> I notice that there is a function `parallellise` in `tiling.jl`, while it is called `parallelise` in the article, I suppose that it is a typo?

Yes, that's indeed a typo. Thanks for mentioning that! Should be fixed by #178.

> I also wonder will you release the latest code as a new version recently? The current released `0.1.0` can not work with Julia after `v1.8`, and I am trying to build some new packaged based on that.

You can also `add GemmKernels@master`, but we should release a new version, indeed. Probably when we finish our work on tensor contractions, @maleadt?
