### ISSUE TITLE
Consider a patch release for the new CUDA versions?

### ISSUE THREAD

**Issue by avik-pal** [JuliaGPU/GemmKernels.jl#192]
Could we get a patch release that supports newer CUDA versions (that seems functional from the CI runs)? Currently the supported version is CUDA 2

**Comment by maleadt** [comment]
> Currently the supported version is CUDA 2

Unless I'm mistaken, GemmKernels.jl has never been tagged yet?

**Comment by avik-pal** [comment]
it has 0.1 tag

**Comment by thomasfaingnaert** [comment]
I think we tagged a release when the paper got published, no?

________________________________

**Comment by maleadt** [comment]
It has a tag, but doesn't seem to exist in General

**Comment by avik-pal** [comment]
https://github.com/JuliaRegistries/General/tree/master/G/GemmKernels this one right?

**Comment by maleadt** [comment]
I'm not sure how I missed that... I'll tag 0.2

**Comment by maleadt** [comment]
https://github.com/JuliaRegistries/General/pull/105145
