### ISSUE TITLE
Register in the General registry?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaGPU/GemmKernels.jl#59]
Could we register this package?

cc: @thomasfaingnaert @maleadt

**Comment by maleadt** [comment]
I'm not sure; the goal was to fold this in to CUDA.jl or even better GPUArrays.jl. That may take a while, though.

Out of curiosity, are you using these GEMM kernels?

**Comment by AriMKatz** [comment]
Can this be useful/generalized for the CPU matmul work?

**Comment by chriselrod** [comment]
FWIW, Octavian.jl is [now doing very well](https://github.com/JuliaLinearAlgebra/Octavian.jl/issues/24#issuecomment-763704038) in the latest implementation of multi-threaded matmul, especially at smaller sizes (...which are cut off in that graph).
Larger sizes I think need some combination of more tuning across architectures and a better performance-model that requires less adjustment across architectures. But I can tune it for a particular machine by running `Optim` for a few days lol.

The approach also looks fairly different [here](https://github.com/JuliaGPU/GemmKernels.jl).
For one thing, it is more implicit in certain respects:
```julia
# (3.3.1) Load a COMPUTE_WARP.M x COMPUTE_WARP.K tile of A from shared memory into registers
a_frags = MArray{Tuple{NUM_FRAGMENTS_M}, Operator.fragtype_a(OPERATOR, SHARED_A_LAYOUT)}(undef)

@unroll for i = 1 : NUM_FRAGMENTS_M
    a_tile = translate_offset(warp_tile.MK, (M = (i-1)*COMPUTE_OP_SHAPE.M, K = 0))
    @inbounds a_frags[i] = transf_sh2rf_a(Operator.load_a(OPERATOR, SHARED_A_LAYOUT, shmem_a, a_tile), a_tile)
end

# (3.3.2) Load a COMPUTE_WARP.K x COMPUTE_WARP.N tile of B from shared memory into registers
b_frags = MArray{Tuple{NUM_FRAGMENTS_N}, Operator.fragtype_b(OPERATOR, SHARED_B_LAYOUT)}(undef)

@unroll for j = 1 : NUM_FRAGMENTS_N
    b_tile = translate_offset(warp_tile.KN, (K = 0, N = (j-1)*COMPUTE_OP_SHAPE.N))
    @inbounds b_frags[j] = transf_sh2rf_b(Operator.load_b(OPERATOR, SHARED_B_LAYOUT, shmem_b, b_tile), b_tile)
end

# (3.3.3) Compute a COMPUTE_WARP.M x COMPUTE_WARP.N x COMPUTE_WARP.K matrix product within one warp
@unroll for i = 1 : NUM_FRAGMENTS_M
    @unroll for j = 1 : NUM_FRAGMENTS_N
        @inbounds c_frags[i, j] = Operator.mma(OPERATOR, a_frags[i], b_frags[j], c_frags[i, j])
    end
end
```
I.e., filling `MArray`s to represent/[encourage the compiler to] load(ing) registers.

LoopVectorization is more explicit, in that it uses LLVM vectors to represent the registers, and intrinsics to map to the desired instructions on them. Before Julia upgraded to LLVM 11, it was even using `call asm` to pick the specific assembly instruction to use (given `FMA`, it would use specifically `vfmadd231p(d/s)`), but [as of LLVM 11](https://reviews.llvm.org/D75016), LLVM now consistently picks the correct instruction, so LoopVectorization is back to emitting LLVM intrinsics.

I'd also have to look more closely to understand what is going on there in the GPU code.
In the CPU kernel, all of the `c_frags[i, j]` contents are held in registers across all the iterations of the microkernel (the `k` loop). I assume that is happening here as well, and is consistent with `c` frag being defined at the start of the function.
But it also looks like there is a lot more going on, with `sync_threads()`, `Layout.threadblock_condition`, and `parallelise`.

**Comment by DilumAluthge** [comment]
> Out of curiosity, are you using these GEMM kernels?

I'm not using them in production. I've just been playing around with them.

As Chris says above, he and I have been working on benchmarking CPU matmul in https://github.com/chriselrod/BLASBenchmarksCPU.jl.

BLASBenchmarksCPU.jl makes it really easy for anyone to run the benchmarks in just a few lines of Julia:
```julia
using Pkg
Pkg.add("BLASBenchmarksCPU")
using BLASBenchmarksCPU
bench_results = BLASBenchmarksCPU.runbench()
BLASBenchmarksCPU.plot(bench_results)
```

On CPU, BLASBenchmarksCPU.jl can compare the following:
1. Octavian.jl
2. Gaius.jl
3. Tullio.jl
4. OpenBLAS
5. MKL
6. BLIS

I was thinking it would be nice if we could make it equally easy for users to benchmark GPU matmul. Some of the things I would like to compare include (but are not limited to):
1. GemmKernels.jl
2. Tullio.jl on the GPU
2. cuBLAS
3. CUTLASS

So, my idea is to create a package BLASBenchmarksGPU.jl (https://github.com/JuliaLinearAlgebra/BLASBenchmarksGPU.jl) that, similar to BLASBenchmarksCPU.jl, lets you run the benchmarks in just a few steps.

**Comment by DilumAluthge** [comment]
To return to the original question of registering GemmKernels:

I'd like to register an initial release of [BLASBenchmarksGPU.jl](https://github.com/JuliaLinearAlgebra/BLASBenchmarksGPU.jl). It depends on GemmKernels, so we'd need to register GemmKernels first.

If, in the future, we move the functionality from GemmKernels to CUDA.jl or GPUArrays.jl, we can deprecate GemmKernels and archive its repo at that time. And I'd migrate BLASBenchmarksGPU to use CUDA.jl or GPUArrays.jl at that time. But I think for now it's fine to register GemmKernels as is.

**Comment by maleadt** [comment]
Sure, fine to me. Maybe a 0.1 version then?

**Comment by DilumAluthge** [comment]
Yeah, 0.1.0 sounds great to me!
